(defun cperl-mode-hook () 
   (let ((prev-a-c abbrevs-changed))
     (define-abbrev-table 'cperl-mode-abbrev-table '(
						     ("if" "if" cperl-electric-keyword 0)
						     ("elsif" "elsif" cperl-electric-keyword 0)
						     ("while" "while" cperl-electric-keyword 0)
						     ("until" "until" cperl-electric-keyword 0)
						     ("unless" "unless" cperl-electric-keyword 0)
						     ("else" "else" cperl-electric-else 0)
						     ("continue" "continue" cperl-electric-else 0)
						     ("for" "for" cperl-electric-keyword 0)
						     ("foreach" "foreach" cperl-electric-keyword 0)
						     ("formy" "formy" cperl-electric-keyword 0)
						     ("foreachmy" "foreachmy" cperl-electric-keyword 0)
						     ("do" "do" cperl-electric-keyword 0)
						     ("=pod" "=pod" cperl-electric-pod 0)
						     ("=over" "=over" cperl-electric-pod 0)
						     ("=head1" "=head1" cperl-electric-pod 0)
						     ("=head2" "=head2" cperl-electric-pod 0)
						     ("pod" "pod" cperl-electric-pod 0)
						     ("over" "over" cperl-electric-pod 0)
						     ("head1" "head1" cperl-electric-pod 0)
						     ("head2" "head2" cperl-electric-pod 0)))
     (setq abbrevs-changed prev-a-c)
     )
   (setq local-abbrev-table cperl-mode-abbrev-table)
)

